config/routes.rb
YogaS::Application.routes.draw do
  
  resources :posts, :path => "/blog"

  root :to => 'home#index'
  
  devise_for :accounts
  

  match ':controller(/:action(/:id(.:format)))'
end

app/models/account.rb
class Account < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :content
  validates_uniqueness_of :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :confirm_logged_in, :except => [:index]
  
  # GET /posts
  # GET /posts.xml
  def index
    if account_signed_in? then
      @posts = Post.all
    else
      @posts = Post.find_all_by_public_flag(true)
    end
  
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.xml
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /posts/1
  # DELETE /posts/1.xml
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
  def confirm_logged_in
    unless account_signed_in?
      flash[:notice] = "Please log in."
      redirect_to new_account_session_path
      return false
    else
      return true
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/index.html.erb
<table id="content_area" cellpadding="5" cellspacing="5">
  <tr>
    <td>
      <img src="images/unknown.jpg" height="300px" align="left" style="padding:10px"/>
      Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).

 
Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et Malorum" by Cicero are also reproduced in their exact original form, accompanied by English versions from the 1914 translation by H. Rackham.

There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
    </td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<link rel="stylesheet" href="/stylesheets/style.css" type="text/css" media="screen" />
<link rel="stylesheet" type="text/css" href="/stylesheets/shortcodes.css">
<link rel="stylesheet" type="text/css" href="/stylesheets/jquery.css">
<!-- TemplateBeginEditable name="doctitle" -->
<title><%= content_for?(:title) ? yield(:title) : "..:: Divine Yoga ::.." %></title>
<!-- TemplateEndEditable -->
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
</head>
<body>
<div class="center-highlight">
<div id="top">
<div class="container">
			<div id="header">
				<a href="/index.html">
					<img src="/images/YogaLogo.gif" alt="Divine Yoga" />					
				</a>
				<div id="menu" class="clearfix">
					<ul id="primary" class="nav">
					<li id="menu-item-191" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-191">
						<a href="#"><%= link_to "Home", root_path %></a>
					</li>
<li id="menu-item-184" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-184"><a href="#"><%= link_to "Blog", posts_path %></a></li>
<li id="menu-item-183" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-183"><a href="#">About Us </a>
  <ul class="sub-menu">
	<li id="menu-item-188" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-188"><a href="#">Sub Menu 1</a></li>
	<li id="menu-item-185" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-185"><a href="#">Sub Menu 2</a></li>
	<li id="menu-item-189" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-189"><a href="#">Nature</a></li>
	<li id="menu-item-190" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-190"><a href="#">People</a></li>
</ul>
</li>
<li id="menu-item-181" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-181"><a href="#">Forum</a></li>
<li id="menu-item-180" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-180"><a href="#">Contact Us </a></li>
</ul>						
					<div id="search-form">
						<form method="get" id="searchform" action="http://www.elegantthemes.com/preview/DeepFocus">
							<input type="text" value="search this site..." name="s" id="searchinput" />

							<input type="image" src="http://www.elegantthemes.com/preview/DeepFocus/wp-content/themes/DeepFocus/images/search-btn.png" id="searchsubmit" />
						</form>
					</div> <!-- end #search-form -->
				</div> <!-- end #menu -->		
			</div> <!-- end #header -->
		</div>
		</div>
<div class="container">
            <% if current_account then %>
              <%= link_to "Sign Out", destroy_account_session_path, :method => :delete %>
            <% else %>
              <%= link_to 'Sign In', new_account_session_path %>
            <% end %>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>

<!-- TemplateBeginEditable name="body" -->

<!-- TemplateEndEditable -->
</div>
<div id="footer">
			<div id="footer-wrapper">
				<div id="footer-center">
					<div class="container">
													
						<p id="copyright">Designed & Powered by  <a href="http://www.elegantthemes.com/" title="Stealth Solutions">Stealth Solutions</a></p>
						
					</div> <!-- end .container -->
				</div> <!-- end #footer-center -->
			</div> <!-- end #footer-wrapper -->
		</div> <!-- end #footer -->
				</div>
	
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label "Public" %><br />
    <%= f.check_box :public_flag %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<table>
  

<% @posts.each do |post| %>
  <tr>
    <td>
      <p><h1><%= link_to post.title, post %></h1></p>
      <p>
      <% if post.content.length > 350 then %>
        <%= post.content[0, 300] %> <%= link_to "Read more", post %>
      <% else %>
        <%= post.content %>
      <% end %>
      </p>
      <% if account_signed_in? %>
      <p><%= link_to 'Edit', edit_post_path(post) if current_account.role == "admin" %> <%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete unless current_account.role == "user"%> </p>
      <% end %>
    <td>
  </tr>
<% end %>
</table>

<br />
<% if account_signed_in? %>
<%= link_to 'New Post', new_post_path if current_account.role == "admin" %>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<table>
  <tr>
    <td>
      <p id="notice"><%= notice %></p>

      <p>
        <h1><%= @post.title %></h1>
      </p>
      <p><%= @post.content %></p> 
      <% if account_signed_in? %>
        <%= link_to 'Edit', edit_post_path(@post) if current_account.role == "admin" %> |
      <% end%>
        <%= link_to 'Back', posts_path %>
    </td>
  </tr>
</table>